# fly.toml app configuration file generated for cloudprinter on 2023-11-06T07:51:55+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cloudprinter"
primary_region = "sin"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
